"""统一测试用例集 v2.0

合并来源:
  - test_data_v6.py (历史35段落，73对话)
  - 新建 文本文档.txt (新增75用例)
  - 4个 GT JSON 文件 (修仙/都市/西幻/斗破)

总条目: 287
总对话: 310

字段说明:
  id: 用例唯一标识 (H-NNN=历史, A-F=分类, GT-风格=长文本提取)
  source: "historical" | "new" | "gt_json"
  category: "dialogue" | "non_dialogue" | "unknown_speaker"
  paragraph: 完整段落文本
  dialogues: 对话列表 [{"text": "...", "speaker": "..."}]
  note: 易错点/备注
"""

UNIFIED_TEST_CASES = [
  {
    "id": "H-001",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "林轩推开客栈的门，对着掌柜说道：\"来一间上房。\"掌柜抬头看了看他，笑道：\"客官来得巧，正好还剩一间。\"",
    "dialogues": [
      {"text": "来一间上房。", "speaker": "林轩"},
      {"text": "客官来得巧，正好还剩一间。", "speaker": "掌柜"},
    ],
    "note": "",
  },
  {
    "id": "H-002",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "小翠端着茶走进书房，轻声道：\"小姐，该用茶了。\"纳兰嫣然放下书卷，头也不抬地问：\"放到桌上吧，老爷回来了吗？\"",
    "dialogues": [
      {"text": "小姐，该用茶了。", "speaker": "小翠"},
      {"text": "放到桌上吧，老爷回来了吗？", "speaker": "纳兰嫣然"},
    ],
    "note": "",
  },
  {
    "id": "H-003",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "苏夜站在山崖边，望着远处的云海说道：\"十年了，我终于回来了。\"身后传来脚步声，一个熟悉的声音响起：\"师弟，别来无恙。\"",
    "dialogues": [
      {"text": "十年了，我终于回来了。", "speaker": "苏夜"},
      {"text": "师弟，别来无恙。", "speaker": "林雪"},
    ],
    "note": "",
  },
  {
    "id": "H-004",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "黑衣人抽出长剑。\"把东西交出来。\"月光照亮了剑刃。苏夜冷笑一声：\"做梦。\"",
    "dialogues": [
      {"text": "把东西交出来。", "speaker": "黑衣人"},
      {"text": "做梦。", "speaker": "苏夜"},
    ],
    "note": "",
  },
  {
    "id": "H-005",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "林雪推门而入。\"林轩，你又在偷懒！\"她叉着腰怒视着躺在床上的少年。林轩懒洋洋地翻了个身：\"姐，让我再睡会儿。\"",
    "dialogues": [
      {"text": "林轩，你又在偷懒！", "speaker": "林雪"},
      {"text": "姐，让我再睡会儿。", "speaker": "林轩"},
    ],
    "note": "",
  },
  {
    "id": "H-006",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "赵天行走进训练场。他沉声说道：\"今天开始，由我负责你们的考核。\"众学员立刻安静下来。",
    "dialogues": [
      {"text": "今天开始，由我负责你们的考核。", "speaker": "赵天行"},
    ],
    "note": "",
  },
  {
    "id": "H-007",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "药老从戒指中飘出。他看了一眼萧炎，缓缓道：\"这枚丹药，你先服下。\"萧炎接过来，毫不犹豫地吞了下去。",
    "dialogues": [
      {"text": "这枚丹药，你先服下。", "speaker": "药老"},
    ],
    "note": "",
  },
  {
    "id": "H-008",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "小翠笑了笑。她轻声说：\"知道了，小姐。\"然后转身离开房间。纳兰嫣然望着她的背影，叹了口气。",
    "dialogues": [
      {"text": "知道了，小姐。", "speaker": "小翠"},
    ],
    "note": "",
  },
  {
    "id": "H-009",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "林轩问道：\"你去参加拍卖会吗？\"小翠摇头：\"不去，我还要准备晚宴。\"他又劝道：\"机会难得，一起去吧。\"",
    "dialogues": [
      {"text": "你去参加拍卖会吗？", "speaker": "林轩"},
      {"text": "不去，我还要准备晚宴。", "speaker": "小翠"},
      {"text": "机会难得，一起去吧。", "speaker": "林轩"},
    ],
    "note": "",
  },
  {
    "id": "H-010",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "萧炎看向药老：\"这枚丹药值多少？\"药老捋了捋胡须：\"至少三万金币。\"萧炎皱眉：\"太贵了。\"",
    "dialogues": [
      {"text": "这枚丹药值多少？", "speaker": "萧炎"},
      {"text": "至少三万金币。", "speaker": "药老"},
      {"text": "太贵了。", "speaker": "萧炎"},
    ],
    "note": "",
  },
  {
    "id": "H-011",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "苏夜举起酒杯：\"敬我们的友谊。\"林雪碰了碰杯：\"敬未来。\"赵天行一饮而尽：\"好酒！\"",
    "dialogues": [
      {"text": "敬我们的友谊。", "speaker": "苏夜"},
      {"text": "敬未来。", "speaker": "林雪"},
      {"text": "好酒！", "speaker": "赵天行"},
    ],
    "note": "",
  },
  {
    "id": "H-012",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "一个白发老者缓缓走来。他捋了捋胡须说道：\"年轻人，你与我有缘。\"苏夜愣住了。",
    "dialogues": [
      {"text": "年轻人，你与我有缘。", "speaker": "白发老者"},
    ],
    "note": "",
  },
  {
    "id": "H-013",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "黑暗中，一个高大的身影浮现。他低沉地说道：\"交出那块玉石，饶你不死。\"林轩握紧拳头：\"休想。\"",
    "dialogues": [
      {"text": "交出那块玉石，饶你不死。", "speaker": "黑衣人"},
      {"text": "休想。", "speaker": "林轩"},
    ],
    "note": "",
  },
  {
    "id": "H-014",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "一位身穿黑袍的骑士走进殿堂。他单膝跪地：\"陛下，前线战报。\"博士抬头：\"念。\"",
    "dialogues": [
      {"text": "陛下，前线战报。", "speaker": "骑士"},
      {"text": "念。", "speaker": "博士"},
    ],
    "note": "",
  },
  {
    "id": "H-015",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "林雪拍了一下桌子。\"这丹药如何？\"药老看向萧炎。萧炎点头道：\"很好，我买了。\"",
    "dialogues": [
      {"text": "这丹药如何？", "speaker": "林雪"},
      {"text": "很好，我买了。", "speaker": "萧炎"},
    ],
    "note": "",
  },
  {
    "id": "H-016",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "纳兰嫣然推门而入。她冷冷说道：\"你来了。\"林轩站起身：\"嫣然姐，好久不见。\"",
    "dialogues": [
      {"text": "你来了。", "speaker": "纳兰嫣然"},
      {"text": "嫣然姐，好久不见。", "speaker": "林轩"},
    ],
    "note": "",
  },
  {
    "id": "H-017",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "苏夜走到窗前。他望着夜色自言自语道：\"什么时候才能结束这一切？\"身后传来轻柔的声音：\"很快了，相信我。\"",
    "dialogues": [
      {"text": "什么时候才能结束这一切？", "speaker": "苏夜"},
      {"text": "很快了，相信我。", "speaker": "伊莉雅"},
    ],
    "note": "",
  },
  {
    "id": "H-018",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"萧炎，你太弱了！\"药老摇头道。萧炎低下头：\"师傅，我会努力的。\"药老叹了口气。",
    "dialogues": [
      {"text": "萧炎，你太弱了！", "speaker": "药老"},
      {"text": "师傅，我会努力的。", "speaker": "萧炎"},
    ],
    "note": "",
  },
  {
    "id": "H-019",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"纳兰嫣然，你变强了。\"林轩认真地说。纳兰嫣然笑道：\"多谢夸奖，你也不差。\"",
    "dialogues": [
      {"text": "纳兰嫣然，你变强了。", "speaker": "林轩"},
      {"text": "多谢夸奖，你也不差。", "speaker": "纳兰嫣然"},
    ],
    "note": "",
  },
  {
    "id": "H-020",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"冲啊！\"众人齐声喊道。他们如潮水般涌向城门。骑士们举起长矛，高呼：\"为了荣耀！\"",
    "dialogues": [
      {"text": "冲啊！", "speaker": "GROUP:CROWD"},
      {"text": "为了荣耀！", "speaker": "骑士们"},
    ],
    "note": "",
  },
  {
    "id": "H-021",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"杀了他们！\"联盟成员怒吼着冲上前。博士冷笑：\"不自量力。\"",
    "dialogues": [
      {"text": "杀了他们！", "speaker": "联盟成员"},
      {"text": "不自量力。", "speaker": "博士"},
    ],
    "note": "",
  },
  {
    "id": "H-022",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"魔法准备好了。\"艾德温举起法杖。伊莉雅点点头：\"开始吧，加尔文在等我们。\"",
    "dialogues": [
      {"text": "魔法准备好了。", "speaker": "艾德温"},
      {"text": "开始吧，加尔文在等我们。", "speaker": "伊莉雅"},
    ],
    "note": "",
  },
  {
    "id": "H-023",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"加尔文，你背叛了我们！\"艾德温怒吼。加尔文平静地回答：\"不，我只是选择了正确的道路。\"",
    "dialogues": [
      {"text": "加尔文，你背叛了我们！", "speaker": "艾德温"},
      {"text": "不，我只是选择了正确的道路。", "speaker": "加尔文"},
    ],
    "note": "",
  },
  {
    "id": "H-024",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"伊莉雅，别冲动。\"骑士拉住她的手。伊莉雅甩开他：\"我要亲手杀了他。\"",
    "dialogues": [
      {"text": "伊莉雅，别冲动。", "speaker": "骑士"},
      {"text": "我要亲手杀了他。", "speaker": "伊莉雅"},
    ],
    "note": "",
  },
  {
    "id": "H-025",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"博士，实验结果如何？\"林轩急切地问道。博士推了推眼镜：\"成功了，这是样本。\"他递出一个试管。",
    "dialogues": [
      {"text": "博士，实验结果如何？", "speaker": "林轩"},
      {"text": "成功了，这是样本。", "speaker": "博士"},
    ],
    "note": "",
  },
  {
    "id": "H-026",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"林轩，你去哪？\"小翠喊住他。林轩头也不回：\"找药老。\"她急忙追上去：\"等等我！\"",
    "dialogues": [
      {"text": "林轩，你去哪？", "speaker": "小翠"},
      {"text": "找药老。", "speaker": "林轩"},
      {"text": "等等我！", "speaker": "小翠"},
    ],
    "note": "",
  },
  {
    "id": "H-027",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"萧炎，别去送死！\"药老抓住他的肩膀。萧炎挣脱开：\"我必须去。\"他转身跳下悬崖。",
    "dialogues": [
      {"text": "萧炎，别去送死！", "speaker": "药老"},
      {"text": "我必须去。", "speaker": "萧炎"},
    ],
    "note": "",
  },
  {
    "id": "H-028",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"你输了。\"苏夜收起剑。黑衣人跪在地上：\"不可能……\"苏夜冷冷地说：\"事实如此。\"",
    "dialogues": [
      {"text": "你输了。", "speaker": "苏夜"},
      {"text": "不可能……", "speaker": "黑衣人"},
      {"text": "事实如此。", "speaker": "苏夜"},
    ],
    "note": "",
  },
  {
    "id": "H-029",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"林雪在吗？\"赵天行敲了敲门。门开了，一个清脆的声音回答：\"她出去了，我是小翠。\"",
    "dialogues": [
      {"text": "林雪在吗？", "speaker": "赵天行"},
      {"text": "她出去了，我是小翠。", "speaker": "小翠"},
    ],
    "note": "",
  },
  {
    "id": "H-030",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"全体注意，向右转！\"骑士队长高声下令。众人齐刷刷地转身。博士满意地点头：\"很好。\"",
    "dialogues": [
      {"text": "全体注意，向右转！", "speaker": "骑士队长"},
      {"text": "很好。", "speaker": "博士"},
    ],
    "note": "",
  },
  {
    "id": "H-031",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"救命！\"一个女声尖叫。苏夜冲进小巷，看到黑衣人正持刀威胁。\"放开她。\"他冷声道。",
    "dialogues": [
      {"text": "救命！", "speaker": "伊莉雅"},
      {"text": "放开她。", "speaker": "苏夜"},
    ],
    "note": "",
  },
  {
    "id": "H-032",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"艾德温，你太冲动了。\"加尔文叹了口气。艾德温反驳道：\"冲动？他杀了我全家！\"",
    "dialogues": [
      {"text": "艾德温，你太冲动了。", "speaker": "加尔文"},
      {"text": "冲动？他杀了我全家！", "speaker": "艾德温"},
    ],
    "note": "",
  },
  {
    "id": "H-033",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"这瓶药水，喝了能解毒。\"白发老者递过瓶子。林轩犹豫了一下：\"我凭什么相信你？\"老者笑了笑：\"信不信由你。\"",
    "dialogues": [
      {"text": "这瓶药水，喝了能解毒。", "speaker": "白发老者"},
      {"text": "我凭什么相信你？", "speaker": "林轩"},
      {"text": "信不信由你。", "speaker": "白发老者"},
    ],
    "note": "",
  },
  {
    "id": "H-034",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"骑士们，冲锋！\"首领挥剑指向敌方。众人齐声呐喊：\"杀！\"博士站在高处，冷冷地看着这一切。",
    "dialogues": [
      {"text": "骑士们，冲锋！", "speaker": "首领"},
      {"text": "杀！", "speaker": "骑士们"},
    ],
    "note": "",
  },
  {
    "id": "H-035",
    "source": "historical",
    "category": "dialogue",
    "paragraph": "\"赵天行，你居然作弊！\"林雪愤怒地指着他。赵天行摊手：\"证据呢？\"她咬牙道：\"我会找到的。\"",
    "dialogues": [
      {"text": "赵天行，你居然作弊！", "speaker": "林雪"},
      {"text": "证据呢？", "speaker": "赵天行"},
      {"text": "我会找到的。", "speaker": "林雪"},
    ],
    "note": "",
  },
  {
    "id": "A1-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明御剑飞过幽石林，下方是连绵的黑色石柱。他记得宗门任务中提到的“幽石林”盛产火属性灵矿。",
    "dialogues": [],
    "note": "地名被引号括住强调，不是角色说话",
  },
  {
    "id": "A1-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "根据古地图所示，“断龙崖”深处有一处上古修士的洞府，但从未有人活着回来。",
    "dialogues": [],
    "note": "地名引号易被误判为对话",
  },
  {
    "id": "A1-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "林雪翻看玉简，上面标注着“陨星谷”三个字，那是筑基期修士的禁地。",
    "dialogues": [],
    "note": "地图标注中的地名",
  },
  {
    "id": "A2-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "石缝间生长着一种名为“地火苔”的低阶灵植，是炼制火属性丹药的辅料。",
    "dialogues": [],
    "note": "物品名被引号强调",
  },
  {
    "id": "A2-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他伸手摘下墙上的“玄冰剑”，剑鞘上结了一层薄霜。",
    "dialogues": [],
    "note": "法宝名称被引号括住",
  },
  {
    "id": "A2-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "炼丹炉里飘出一股异香，那是“九转还魂丹”即将成丹的征兆。",
    "dialogues": [],
    "note": "丹药名被误判为对话",
  },
  {
    "id": "A3-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "“轰！”一声巨响从洞府深处传来，整个山洞都在颤抖。",
    "dialogues": [],
    "note": "拟声词被引号括住，非角色说话",
  },
  {
    "id": "A3-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "“嗖——”一支灵箭破空而至，钉在他脚前半寸的地面上。",
    "dialogues": [],
    "note": "箭矢破空声拟声词",
  },
  {
    "id": "A3-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "“咔嚓！”他踩断了一根枯枝，惊动了草丛中的灵兽。",
    "dialogues": [],
    "note": "环境音效拟声词",
  },
  {
    "id": "A4-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明知道自己属于那种“求稳”的散修，从不冒险进入未探明的区域。",
    "dialogues": [],
    "note": "形容词被引号强调，非对话",
  },
  {
    "id": "A4-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他的修炼方式可以用一个词概括——“苦修”，日复一日打磨灵力。",
    "dialogues": [],
    "note": "概括性词汇被引号括住",
  },
  {
    "id": "A4-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "面对金丹期的妖兽，他选择了“暂避锋芒”的策略，绕道而行。",
    "dialogues": [],
    "note": "成语策略被引号强调",
  },
  {
    "id": "A5-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他站在悬崖边，“跳，还是不跳”这个问题在脑海中反复盘旋。",
    "dialogues": [],
    "note": "内心独白中的问题引用，非实际说话",
  },
  {
    "id": "A5-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "林雪脑海里闪过一个念头：“如果失败了怎么办？”她攥紧了拳头。",
    "dialogues": [],
    "note": "内心独白被引号引用，非开口说话",
  },
  {
    "id": "A5-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明暗自思忖：“这老家伙八成在骗我。”但表面上仍不动声色。",
    "dialogues": [],
    "note": "内心想法被引号标记，需区分于对话",
  },
  {
    "id": "B1-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他在断崖附近意外得到一枚“丹方玉简”。丹方玉简表面刻满蝌蚪文，记录着上古炼丹术。\"无对话，仅旁白（若系统认为有对话则错误）\"",
    "dialogues": [],
    "note": "物品名“丹方玉简”可能被NER误判为人物",
  },
  {
    "id": "B1-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "灵兽袋里装着一只“噬金蚁”。噬金蚁虽然个头小，但能啃食法器。\"无对话\"",
    "dialogues": [],
    "note": "灵兽名被当成角色名",
  },
  {
    "id": "B1-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他从储物袋中取出一柄“青锋剑”。青锋剑剑身上有裂纹，显然经历过多场战斗。\"无对话\"",
    "dialogues": [],
    "note": "法宝名被误判为人物",
  },
  {
    "id": "B2-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他来自遥远的“仓央洲”。仓央洲的修炼资源比这边丰富得多，但妖兽也更凶猛。\"无对话\"",
    "dialogues": [],
    "note": "地名被误判为角色",
  },
  {
    "id": "B2-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "“黑风谷”常年被毒雾笼罩，谷中寸草不生。曾有金丹修士进入后再也没出来。\"无对话\"",
    "dialogues": [],
    "note": "险地地名被误认为人物",
  },
  {
    "id": "B2-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "传送阵的目的地是“天元城”。天元城是方圆万里最大的修士聚集地。\"无对话\"",
    "dialogues": [],
    "note": "城池名被误判",
  },
  {
    "id": "B3-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他身上穿着“张家”的罩衫。张家在仓央洲是个小家族，擅长炼丹。\"无对话\"",
    "dialogues": [],
    "note": "家族名被当成个人角色",
  },
  {
    "id": "B3-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他加入了“青云宗”的外门。青云宗每三年招收一次弟子，竞争激烈。\"无对话\"",
    "dialogues": [],
    "note": "宗门名被误判为人物",
  },
  {
    "id": "B3-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "“万宝楼”的招牌在街角闪闪发光。万宝楼出售各种高阶法器，价格不菲。\"无对话\"",
    "dialogues": [],
    "note": "组织/商会名被误判",
  },
  {
    "id": "B4-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他的护体“真元”在刚才的战斗中消耗大半，经脉隐隐作痛。\"无对话\"",
    "dialogues": [],
    "note": "修炼概念被误认为角色",
  },
  {
    "id": "B4-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "那个被困在祭坛底部的“元婴”向他发出求救的意念波动。元婴浑身缠绕着黑气。\"无对话\"",
    "dialogues": [],
    "note": "境界/元神名被误判为独立角色",
  },
  {
    "id": "B4-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他苦苦修炼了三十年，终于触摸到了“金丹”的门槛。金丹一成，寿元大增。\"无对话\"",
    "dialogues": [],
    "note": "境界名被误判",
  },
  {
    "id": "B5-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他的神魂感知力“远超”同阶修士，能提前预判危险。\"无对话\"",
    "dialogues": [],
    "note": "程度副词被当成角色名",
  },
  {
    "id": "B5-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "林雪的炼丹术“精湛”无比，连长老都称赞不已。\"无对话\"",
    "dialogues": [],
    "note": "形容词被误判",
  },
  {
    "id": "B5-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "这股灵力波动“诡异”异常，不像是人类修士发出的。\"无对话\"",
    "dialogues": [],
    "note": "形容词被误判",
  },
  {
    "id": "C1-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "林雪仔细端详着这枚丹药，眉头紧锁。 \"这丹药如何？\"林雪拍了一下桌子，神色凝重。",
    "dialogues": [
      {"text": "这丹药如何？", "speaker": "林雪"},
    ],
    "note": "说话动词在对话之后，需从后文提取",
  },
  {
    "id": "C1-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "孙项明望着远处的黑雾，深吸一口气。 \"该进去了。\"他握紧剑柄，踏入迷雾之中。",
    "dialogues": [
      {"text": "该进去了。", "speaker": "孙项明"},
    ],
    "note": "后文代词“他”指示说话人",
  },
  {
    "id": "C1-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "白发老者拄着拐杖，颤巍巍地抬起头。 \"小娃娃，过来。\"老者向他招了招手。",
    "dialogues": [
      {"text": "小娃娃，过来。", "speaker": "白发老者"},
    ],
    "note": "说话人描述在后文",
  },
  {
    "id": "C2-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"老孙，你来啦！\"郭垣笑眯眯地迎上来。\"郭道友。\"孙项明点点头，态度冷淡。\"嘿，这次打算去哪探？\"\"老地方碰碰运气。\"",
    "dialogues": [
      {"text": "老孙，你来啦！", "speaker": "郭垣"},
      {"text": "郭道友。", "speaker": "孙项明"},
      {"text": "嘿，这次打算去哪探？", "speaker": "郭垣"},
      {"text": "老地方碰碰运气。", "speaker": "孙项明"},
    ],
    "note": "同一段落中多人轮流说话，需正确区分每个对话的说话人",
  },
  {
    "id": "C2-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"掌门，弟子愿前往。\"林雪抱拳道。\"不行，你修为太弱。\"掌门摇头。\"那我陪她一起去。\"萧炎站了出来。",
    "dialogues": [
      {"text": "掌门，弟子愿前往。", "speaker": "林雪"},
      {"text": "不行，你修为太弱。", "speaker": "掌门"},
      {"text": "那我陪她一起去。", "speaker": "萧炎"},
    ],
    "note": "三个角色连续对话，动词位置不同",
  },
  {
    "id": "C2-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"师兄，你受伤了？\"小师妹惊呼。\"无妨，皮外伤。\"他捂住肩膀。\"快服下这枚疗伤丹。\"",
    "dialogues": [
      {"text": "师兄，你受伤了？", "speaker": "小师妹"},
      {"text": "无妨，皮外伤。", "speaker": "师兄（他）"},
      {"text": "快服下这枚疗伤丹。", "speaker": "小师妹"},
    ],
    "note": "第二句说话人用代词“他”，需消解",
  },
  {
    "id": "C3-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "林轩正坐在树下偷懒，忽然听到一阵脚步声。 \"林轩，你又在偷懒！\"林雪双手叉腰站在他面前。",
    "dialogues": [
      {"text": "林轩，你又在偷懒！", "speaker": "林雪"},
    ],
    "note": "“林轩”在引号内开头但为听话人，说话人是林雪",
  },
  {
    "id": "C3-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "萧炎在擂台上连连败退，对手冷笑一声。 \"萧炎，认输吧，你不是我的对手。\"对方剑尖直指他的咽喉。",
    "dialogues": [
      {"text": "萧炎，认输吧，你不是我的对手。", "speaker": "对手"},
    ],
    "note": "被称呼的“萧炎”不是说话人",
  },
  {
    "id": "C3-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "孙项明刚刚踏入洞府，黑暗中传来一个沙哑的声音。 \"孙项明，我等了你很久了。\"一个黑影从角落缓缓走出。",
    "dialogues": [
      {"text": "孙项明，我等了你很久了。", "speaker": "未知"},
    ],
    "note": "对话开头称呼“孙项明”，说话人是别人",
  },
  {
    "id": "C4-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"让开！\"白发老者拄着拐杖，声音沙哑。",
    "dialogues": [
      {"text": "让开！", "speaker": "白发老者"},
    ],
    "note": "描述性称呼“白发老者”，核心词“老者”应与简称匹配",
  },
  {
    "id": "C4-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"这枚丹药归我了。\"身穿黑袍的年轻人一把夺过玉瓶。",
    "dialogues": [
      {"text": "这枚丹药归我了。", "speaker": "黑袍年轻人"},
    ],
    "note": "修饰词+核心词，需识别核心词",
  },
  {
    "id": "C4-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"大胆！竟敢擅闯禁地。\"守阵老者怒目圆睁，手中法诀已经掐好。",
    "dialogues": [
      {"text": "大胆！竟敢擅闯禁地。", "speaker": "守阵老者"},
    ],
    "note": "“守阵”为修饰，核心“老者”",
  },
  {
    "id": "C5-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "萧炎收起玄重尺。他长出一口气，\"终于突破了。\"",
    "dialogues": [
      {"text": "终于突破了。", "speaker": "萧炎"},
    ],
    "note": "代词“他”指向前文角色",
  },
  {
    "id": "C5-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "林雪把丹方递给孙项明。她低声叮嘱道，\"小心保管，别弄丢了。\"",
    "dialogues": [
      {"text": "小心保管，别弄丢了。", "speaker": "林雪"},
    ],
    "note": "代词“她”指代林雪",
  },
  {
    "id": "C5-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "白发老者和黑衣少年对峙良久。老者忽然开口，\"你师父欠我一条命。\"",
    "dialogues": [
      {"text": "你师父欠我一条命。", "speaker": "白发老者"},
    ],
    "note": "称呼“老者”指代前文“白发老者”",
  },
  {
    "id": "C6-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "萧炎望着林轩的背影，暗暗称赞。\"林轩的剑法果然厉害。\"",
    "dialogues": [
      {"text": "林轩的剑法果然厉害。", "speaker": "萧炎"},
    ],
    "note": "对话中的“林轩”是所有格，不是说话人",
  },
  {
    "id": "C6-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "孙项明听到这个消息，心中冷笑。\"张家的丹药也不过如此。\"",
    "dialogues": [
      {"text": "张家的丹药也不过如此。", "speaker": "孙项明"},
    ],
    "note": "“张家”在对话中作为被评价对象，非说话人",
  },
  {
    "id": "C6-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "林雪翻开古籍，念出上面的一行字。\"萧炎的陨落之地，便是此处。\"",
    "dialogues": [
      {"text": "萧炎的陨落之地，便是此处。", "speaker": "林雪"},
    ],
    "note": "“萧炎”出现在对话中但为宾语，说话人是林雪",
  },
  {
    "id": "D1-1",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "\"把东西交出来。\"",
    "dialogues": [
      {"text": "把东西交出来。", "speaker": "未知"},
    ],
    "note": "孤立无上下文，无法判定说话人",
  },
  {
    "id": "D1-2",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "\"别跑！\"",
    "dialogues": [
      {"text": "别跑！", "speaker": "未知"},
    ],
    "note": "无任何角色信息",
  },
  {
    "id": "D2-1",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "人群中爆发出一阵骚动。\"太强了！\"\"怎么可能！\"\"这家伙是什么来头？\"",
    "dialogues": [
      {"text": "太强了！", "speaker": "未知"},
      {"text": "怎么可能！", "speaker": "未知"},
      {"text": "这家伙是什么来头？", "speaker": "未知"},
    ],
    "note": "多人场景，无法确定具体谁说的",
  },
  {
    "id": "D2-2",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "战场上一片混乱，刀光剑影中夹杂着怒吼。\"给我杀！\"\"撤退！\"\"救命啊！\"",
    "dialogues": [
      {"text": "给我杀！", "speaker": "未知"},
      {"text": "撤退！", "speaker": "未知"},
      {"text": "救命啊！", "speaker": "未知"},
    ],
    "note": "嘈杂环境，说话人不可知",
  },
  {
    "id": "D3-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "古籍上记载：\"天火三玄变，第一变：熔岩体。\"",
    "dialogues": [],
    "note": "书籍引用，非角色说话",
  },
  {
    "id": "D3-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "石碑上刻着一行古老的铭文：\"入此门者，当弃一切希望。\"",
    "dialogues": [],
    "note": "石碑文字非对话",
  },
  {
    "id": "D3-3",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "传音符中传来一个模糊的声音：\"速来支援……敌……太多……\"",
    "dialogues": [
      {"text": "速来支援……敌……太多……", "speaker": "未知"},
    ],
    "note": "传音符信息但说话人不明",
  },
  {
    "id": "E1-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"老夫自有分寸。\"药尘捋着胡须。 \"那就有劳药老了。\"萧炎抱拳。",
    "dialogues": [
      {"text": "老夫自有分寸。", "speaker": "药尘"},
      {"text": "那就有劳药老了。", "speaker": "萧炎"},
    ],
    "note": "全名与简称需合并为同一角色",
  },
  {
    "id": "E1-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"萧炎，你太冒进了。\"药老摇头。 \"是，药老教训得对。\"萧炎低下头。",
    "dialogues": [
      {"text": "萧炎，你太冒进了。", "speaker": "药老"},
      {"text": "是，药老教训得对。", "speaker": "萧炎"},
    ],
    "note": "需识别同一角色的不同称呼",
  },
  {
    "id": "E1-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"林雪，这是你的丹药。\"孙项明递过玉瓶。 \"多谢孙兄。\"林雪微微一笑。",
    "dialogues": [
      {"text": "林雪，这是你的丹药。", "speaker": "孙项明"},
      {"text": "多谢孙兄。", "speaker": "林雪"},
    ],
    "note": "姓+兄的称呼需匹配",
  },
  {
    "id": "E2-1",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"不想死就滚开。\"黑衣老者冷冷道。 \"是，是……老者饶命！\"一个散修跪地求饶。",
    "dialogues": [
      {"text": "不想死就滚开。", "speaker": "黑衣老者"},
      {"text": "是，是……老者饶命！", "speaker": "散修"},
    ],
    "note": "修饰词去掉后核心词匹配",
  },
  {
    "id": "E2-2",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"小娃娃，此地危险。\"拄拐老妪沙哑地说。 \"老妪，敢问前方是什么地方？\"年轻修士恭敬问道。",
    "dialogues": [
      {"text": "小娃娃，此地危险。", "speaker": "拄拐老妪"},
      {"text": "老妪，敢问前方是什么地方？", "speaker": "年轻修士"},
    ],
    "note": "修饰词“拄拐”可省略",
  },
  {
    "id": "E2-3",
    "source": "new",
    "category": "dialogue",
    "paragraph": "\"哼，不自量力。\"金袍少年冷笑一声。 \"少年，你太狂妄了。\"中年修士拔出长剑。",
    "dialogues": [
      {"text": "哼，不自量力。", "speaker": "金袍少年"},
      {"text": "少年，你太狂妄了。", "speaker": "中年修士"},
    ],
    "note": "核心词“少年”匹配",
  },
  {
    "id": "F1-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "石碑上刻着几行古老的文字。 \"入此门者，当弃一切希望。\"萧炎皱了皱眉。",
    "dialogues": [],
    "note": "石碑铭文，非角色说话",
  },
  {
    "id": "F1-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "卷轴缓缓展开，上面用金字写着： \"天劫降临，万物俱灭。\"林雪脸色煞白。",
    "dialogues": [],
    "note": "卷轴文字被误判为对话",
  },
  {
    "id": "F1-3",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "传音符闪烁了一下，里面传出一个焦急的声音： \"黑风谷出现异动，所有弟子速回！\"但声音太过模糊，无法辨认是谁。",
    "dialogues": [
      {"text": "黑风谷出现异动，所有弟子速回！", "speaker": "未知"},
    ],
    "note": "传音符内容，但说话人未知",
  },
  {
    "id": "F2-1",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "\"如果能活着回去……\"这个念头刚冒出来就被他压了下去。",
    "dialogues": [],
    "note": "内心想法被引号引用，不是开口说话",
  },
  {
    "id": "F2-2",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他心中默念：“一定要撑住。”然后咬牙站了起来。",
    "dialogues": [],
    "note": "默念属于内心活动，非实际对话",
  },
  {
    "id": "F2-3",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明在黑暗中自语道：“不行，得想个办法。”但他并未出声。",
    "dialogues": [],
    "note": "“自语道”有时指内心独白，需根据上下文区分；此处可设为旁白非对话\n# F2-3-补",
  },
  {
    "id": "D1-3",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "\"你竟敢背叛我！\"",
    "dialogues": [
      {"text": "你竟敢背叛我！", "speaker": "未知"},
    ],
    "note": "完全孤立的一句话，无任何角色信息",
  },
  {
    "id": "D2-3",
    "source": "new",
    "category": "unknown_speaker",
    "paragraph": "广场上数千弟子齐声高呼，声音震天。\"恭迎掌门出关！\"\"掌门万寿无疆！\"\"我等誓死追随！\"",
    "dialogues": [
      {"text": "恭迎掌门出关！", "speaker": "未知"},
      {"text": "掌门万寿无疆！", "speaker": "未知"},
      {"text": "我等誓死追随！", "speaker": "未知"},
    ],
    "note": "群体呼喊，无法确定个体说话人",
  },
  {
    "id": "B1-混",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "萧炎从怀中取出一卷\"丹方玉简\"。丹方玉简表面微光流转。\"这东西值多少钱？\"药老眯起眼睛。萧炎笑了笑，\"无价之宝。\"",
    "dialogues": [
      {"text": "这东西值多少钱？", "speaker": "药老"},
      {"text": "无价之宝。", "speaker": "萧炎"},
    ],
    "note": "物品名\"丹方玉简\"不应被创建为角色，但对话说话人应正确识别",
  },
  {
    "id": "B2-混",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "传送阵将他们送到了\"仓央洲\"的边缘。仓央洲灵气稀薄，一片荒芜。\"这就是你说的宝地？\"林雪皱眉。\"耐心点，宝藏在地底。\"孙项明走在前面。",
    "dialogues": [
      {"text": "这就是你说的宝地？", "speaker": "林雪"},
      {"text": "耐心点，宝藏在地底。", "speaker": "孙项明"},
    ],
    "note": "地名\"仓央洲\"不应被创建为角色",
  },
  {
    "id": "B3-混",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他换上了\"张家\"的罩衫。张家在仓央洲虽是小家族，但炼丹术远近闻名。\"听说张家最近收了一批好药材。\"林雪在孙项明耳边低语。",
    "dialogues": [
      {"text": "听说张家最近收了一批好药材。", "speaker": "林雪"},
    ],
    "note": "组织名\"张家\"在对话中出现，但不表示\"张家\"是说话人",
  },
  {
    "id": "B4-混",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明的护体\"真元\"被一掌打散，嘴角渗血。\"哼，就这点本事？\"郭垣狞笑逼近。孙项明咬牙道，\"还没完。\"",
    "dialogues": [
      {"text": "哼，就这点本事？", "speaker": "郭垣"},
      {"text": "还没完。", "speaker": "孙项明"},
    ],
    "note": "概念词\"真元\"不应被创建为角色",
  },
  {
    "id": "B5-混",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "他的神魂感知力\"远超\"同阶修士。林雪感叹道，\"这家伙简直是个怪物。\"萧炎点头，\"没错，他修习的功法也很特殊。\"",
    "dialogues": [
      {"text": "这家伙简直是个怪物。", "speaker": "林雪"},
      {"text": "没错，他修习的功法也很特殊。", "speaker": "萧炎"},
    ],
    "note": "形容词\"远超\"不应被创建为角色，但对话说话人需正确匹配",
  },
  {
    "id": "F2-3-补",
    "source": "new",
    "category": "non_dialogue",
    "paragraph": "孙项明盘坐黑暗中，心神沉入识海。一个念头浮现：“不行，得想个办法。”他睁开眼，已有计较。",
    "dialogues": [],
    "note": "心神中的念头用引号标出，属于内心活动，非开口说话",
  },
  {
    "id": "GT-修仙-001",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，您终于醒了！”",
    "dialogues": [
      {"text": "少爷，您终于醒了！", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-002",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“小翠，我睡了多久？”",
    "dialogues": [
      {"text": "小翠，我睡了多久？", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-003",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，您昏迷了整整三天！”",
    "dialogues": [
      {"text": "少爷，您昏迷了整整三天！", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-004",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“轩儿！你终于醒了！”",
    "dialogues": [
      {"text": "轩儿！你终于醒了！", "speaker": "林天豪"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-005",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“父亲。”",
    "dialogues": [
      {"text": "父亲。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-006",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“轩儿，你感觉如何？”",
    "dialogues": [
      {"text": "轩儿，你感觉如何？", "speaker": "林天豪"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-007",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“父亲放心，孩儿已经无碍。”",
    "dialogues": [
      {"text": "父亲放心，孩儿已经无碍。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-008",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“那就好，那就好。”",
    "dialogues": [
      {"text": "那就好，那就好。", "speaker": "林天豪"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-009",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“是，父亲。”",
    "dialogues": [
      {"text": "是，父亲。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-010",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“既来之，则安之。”",
    "dialogues": [
      {"text": "既来之，则安之。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-011",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，老奴是王管家。”",
    "dialogues": [
      {"text": "少爷，老奴是王管家。", "speaker": "王管家"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-012",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“进来吧。”",
    "dialogues": [
      {"text": "进来吧。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-013",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，这是您要的书籍。”",
    "dialogues": [
      {"text": "少爷，这是您要的书籍。", "speaker": "王管家"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-014",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“辛苦王叔了。”",
    "dialogues": [
      {"text": "辛苦王叔了。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-015",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷客气了，老奴告退。”",
    "dialogues": [
      {"text": "少爷客气了，老奴告退。", "speaker": "王管家"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-016",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“看来，我需要尽快提升实力。”",
    "dialogues": [
      {"text": "看来，我需要尽快提升实力。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-017",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，您休息一下吧。”",
    "dialogues": [
      {"text": "少爷，您休息一下吧。", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-018",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“好。”",
    "dialogues": [
      {"text": "好。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-019",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，您真厉害！”",
    "dialogues": [
      {"text": "少爷，您真厉害！", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-020",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“还差得远呢。”",
    "dialogues": [
      {"text": "还差得远呢。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-021",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷要去武馆？”",
    "dialogues": [
      {"text": "少爷要去武馆？", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-022",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“府里太安逸了，我需要更大的压力。”",
    "dialogues": [
      {"text": "府里太安逸了，我需要更大的压力。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-023",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“要下雨了。”",
    "dialogues": [
      {"text": "要下雨了。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-024",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“少爷，我们快回去吧！”",
    "dialogues": [
      {"text": "少爷，我们快回去吧！", "speaker": "小翠"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-025",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这一世，我一定要站在这个世界的巅峰！”",
    "dialogues": [
      {"text": "这一世，我一定要站在这个世界的巅峰！", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-026",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“让开！让开！”",
    "dialogues": [
      {"text": "让开！让开！", "speaker": "赵虎"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-027",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“那是赵家的少爷赵虎。”",
    "dialogues": [
      {"text": "那是赵家的少爷赵虎。", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-028",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“淬体境三重？这么厉害！”",
    "dialogues": [
      {"text": "淬体境三重？这么厉害！", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-029",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“可不是嘛，赵家可是我们天元城的三大家族之一！”",
    "dialogues": [
      {"text": "可不是嘛，赵家可是我们天元城的三大家族之一！", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-030",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“哟，这不是林家的废物少爷吗？”",
    "dialogues": [
      {"text": "哟，这不是林家的废物少爷吗？", "speaker": "赵虎"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-031",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“赵少爷说笑了。让路。”",
    "dialogues": [
      {"text": "赵少爷说笑了。让路。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-032",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“怎么？不敢说话？”",
    "dialogues": [
      {"text": "怎么？不敢说话？", "speaker": "赵虎"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-033",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这林家少爷，胆子不小啊！”",
    "dialogues": [
      {"text": "这林家少爷，胆子不小啊！", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-034",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“是啊，敢这么跟赵虎说话！”",
    "dialogues": [
      {"text": "是啊，敢这么跟赵虎说话！", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-035",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“请出示身份证明。”",
    "dialogues": [
      {"text": "请出示身份证明。", "speaker": "考官"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-036",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“听说这次考核很严格，要通过三关才能成为正式学员！”",
    "dialogues": [
      {"text": "听说这次考核很严格，要通过三关才能成为正式学员！", "speaker": "路人"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-037",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“下一个，林轩！”",
    "dialogues": [
      {"text": "下一个，林轩！", "speaker": "考官"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-038",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“请出拳。”",
    "dialogues": [
      {"text": "请出拳。", "speaker": "考官"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-039",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“三百斤！”",
    "dialogues": [
      {"text": "三百斤！", "speaker": "考官"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-040",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“恭喜你，林轩，你被录取了！”",
    "dialogues": [
      {"text": "恭喜你，林轩，你被录取了！", "speaker": "考官"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-041",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“多谢考官。”",
    "dialogues": [
      {"text": "多谢考官。", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-042",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“林轩，你来得真早！”",
    "dialogues": [
      {"text": "林轩，你来得真早！", "speaker": "李铁"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-043",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“李铁。你怎么也这么早？”",
    "dialogues": [
      {"text": "李铁。你怎么也这么早？", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-044",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“哈哈，我这不是怕落后嘛！”",
    "dialogues": [
      {"text": "哈哈，我这不是怕落后嘛！", "speaker": "李铁"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-045",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“对了，听说今天有大师兄的授课！”",
    "dialogues": [
      {"text": "对了，听说今天有大师兄的授课！", "speaker": "李铁"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-046",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“淬体境九重？”",
    "dialogues": [
      {"text": "淬体境九重？", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-047",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“今天，我要讲的是武道的根基——淬体！”",
    "dialogues": [
      {"text": "今天，我要讲的是武道的根基——淬体！", "speaker": "陈风"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-048",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“武道一途，没有捷径可走，唯有勤修苦练！”",
    "dialogues": [
      {"text": "武道一途，没有捷径可走，唯有勤修苦练！", "speaker": "陈风"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-049",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“你很不错，好好努力，将来必成大器！”",
    "dialogues": [
      {"text": "你很不错，好好努力，将来必成大器！", "speaker": "陈风"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-050",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“多谢大师兄指点！”",
    "dialogues": [
      {"text": "多谢大师兄指点！", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-051",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“林轩！该吃饭了！”",
    "dialogues": [
      {"text": "林轩！该吃饭了！", "speaker": "李铁"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-052",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“来了！”",
    "dialogues": [
      {"text": "来了！", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-053",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“林轩，你的进步真快！”",
    "dialogues": [
      {"text": "林轩，你的进步真快！", "speaker": "李铁"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-054",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“是你让着我。再来！”",
    "dialogues": [
      {"text": "是你让着我。再来！", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-修仙-055",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“明天，又是新的一天！”",
    "dialogues": [
      {"text": "明天，又是新的一天！", "speaker": "林轩"},
    ],
    "note": "来源: test_novel.txt | 风格: 修仙",
  },
  {
    "id": "GT-都市异能-001",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，你在这里！”",
    "dialogues": [
      {"text": "苏夜，你在这里！", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-002",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“林雪，你怎么上来了？”",
    "dialogues": [
      {"text": "林雪，你怎么上来了？", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-003",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“公司出事了。”",
    "dialogues": [
      {"text": "公司出事了。", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-004",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“今天有个神秘组织来公司搜查”",
    "dialogues": [
      {"text": "今天有个神秘组织来公司搜查", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-005",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“他们怎么知道这里有异能者？”",
    "dialogues": [
      {"text": "他们怎么知道这里有异能者？", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-006",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，来会议室一趟。”",
    "dialogues": [
      {"text": "苏夜，来会议室一趟。", "speaker": "老陈"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-007",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏先生，我们是暗影会的调查员。”",
    "dialogues": [
      {"text": "苏先生，我们是暗影会的调查员。", "speaker": "黑衣人"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-008",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我不知道你们在说什么。”",
    "dialogues": [
      {"text": "我不知道你们在说什么。", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-009",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，快来老地方！”",
    "dialogues": [
      {"text": "苏夜，快来老地方！", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-010",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这是赵天行赵大哥。”",
    "dialogues": [
      {"text": "这是赵天行赵大哥。", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-011",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我是华夏异能者联盟的负责人。”",
    "dialogues": [
      {"text": "我是华夏异能者联盟的负责人。", "speaker": "赵天行"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-012",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“明天开始，你来联盟总部报道。”",
    "dialogues": [
      {"text": "明天开始，你来联盟总部报道。", "speaker": "赵天行"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-013",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“暗影会的人来了！”",
    "dialogues": [
      {"text": "暗影会的人来了！", "speaker": "联盟成员"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-014",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，你跟我去前线！”",
    "dialogues": [
      {"text": "苏夜，你跟我去前线！", "speaker": "赵天行"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-015",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“干得好，苏夜！”",
    "dialogues": [
      {"text": "干得好，苏夜！", "speaker": "赵天行"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-016",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我建议潜入基地。”",
    "dialogues": [
      {"text": "我建议潜入基地。", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-017",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“太危险了。”",
    "dialogues": [
      {"text": "太危险了。", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-018",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“样本准备好了吗？”",
    "dialogues": [
      {"text": "样本准备好了吗？", "speaker": "博士"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-019",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这不是科学，这是犯罪！”",
    "dialogues": [
      {"text": "这不是科学，这是犯罪！", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-020",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，你这次立了大功。”",
    "dialogues": [
      {"text": "苏夜，你这次立了大功。", "speaker": "赵天行"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-021",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这是大家共同努力的结果。”",
    "dialogues": [
      {"text": "这是大家共同努力的结果。", "speaker": "苏夜"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-022",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“苏夜，你太棒了！”",
    "dialogues": [
      {"text": "苏夜，你太棒了！", "speaker": "林雪"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-都市异能-023",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“为了守护这个世界！”",
    "dialogues": [
      {"text": "为了守护这个世界！", "speaker": "三人"},
    ],
    "note": "来源: test_novel_urban.txt | 风格: 都市异能",
  },
  {
    "id": "GT-西幻-001",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“北方有异动。”",
    "dialogues": [
      {"text": "北方有异动。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-002",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我能感觉到魔力的波动。”",
    "dialogues": [
      {"text": "我能感觉到魔力的波动。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-003",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“那不是雷声。”",
    "dialogues": [
      {"text": "那不是雷声。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-004",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“是炎魔，至少有三只。”",
    "dialogues": [
      {"text": "是炎魔，至少有三只。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-005",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“情况如何？”",
    "dialogues": [
      {"text": "情况如何？", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-006",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“炎魔入侵，立即组织防御。”",
    "dialogues": [
      {"text": "炎魔入侵，立即组织防御。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-007",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“是！”",
    "dialogues": [
      {"text": "是！", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-008",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“射击！”",
    "dialogues": [
      {"text": "射击！", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-009",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“弓箭无效！”",
    "dialogues": [
      {"text": "弓箭无效！", "speaker": "骑士"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-010",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“换银箭！”",
    "dialogues": [
      {"text": "换银箭！", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-011",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“它们在试探我们的实力。”",
    "dialogues": [
      {"text": "它们在试探我们的实力。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-012",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“根据古籍记载，炎魔不会无缘无故出现。”",
    "dialogues": [
      {"text": "根据古籍记载，炎魔不会无缘无故出现。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-013",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“一定是有人召唤了它们。”",
    "dialogues": [
      {"text": "一定是有人召唤了它们。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-014",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“巡逻队在北边发现了痕迹。”",
    "dialogues": [
      {"text": "巡逻队在北边发现了痕迹。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-015",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“有人类与炎魔勾结？”",
    "dialogues": [
      {"text": "有人类与炎魔勾结？", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-016",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“很有可能。”",
    "dialogues": [
      {"text": "很有可能。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-017",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“明天一早，我带人去北方调查。”",
    "dialogues": [
      {"text": "明天一早，我带人去北方调查。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-018",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我和你一起去。”",
    "dialogues": [
      {"text": "我和你一起去。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-019",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我留守哨站，组织防御。”",
    "dialogues": [
      {"text": "我留守哨站，组织防御。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-020",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“魔力波动越来越强了。”",
    "dialogues": [
      {"text": "魔力波动越来越强了。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-021",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“防御！”",
    "dialogues": [
      {"text": "防御！", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-022",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“它变强了。”",
    "dialogues": [
      {"text": "它变强了。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-023",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“就是现在！”",
    "dialogues": [
      {"text": "就是现在！", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-024",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“没事吧？”",
    "dialogues": [
      {"text": "没事吧？", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-025",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“没事，继续前进。”",
    "dialogues": [
      {"text": "没事，继续前进。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-026",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“他在召唤更多的炎魔。”",
    "dialogues": [
      {"text": "他在召唤更多的炎魔。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-027",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“分三组，同时攻击。伊莉雅，你负责打断仪式。”",
    "dialogues": [
      {"text": "分三组，同时攻击。伊莉雅，你负责打断仪式。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-028",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“明白。”",
    "dialogues": [
      {"text": "明白。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-029",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“莫洛克？”",
    "dialogues": [
      {"text": "莫洛克？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-030",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“没想到你会记得我。”",
    "dialogues": [
      {"text": "没想到你会记得我。", "speaker": "莫洛克"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-031",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“你为什么要召唤炎魔？”",
    "dialogues": [
      {"text": "你为什么要召唤炎魔？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-032",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“为了力量！”",
    "dialogues": [
      {"text": "为了力量！", "speaker": "莫洛克"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-033",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“你疯了！炎魔只会毁灭一切！”",
    "dialogues": [
      {"text": "你疯了！炎魔只会毁灭一切！", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-034",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“情况比我们想象的严重。”",
    "dialogues": [
      {"text": "情况比我们想象的严重。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-035",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“足以摧毁整个哨站。”",
    "dialogues": [
      {"text": "足以摧毁整个哨站。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-036",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们必须请求支援。”",
    "dialogues": [
      {"text": "我们必须请求支援。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-037",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“在支援到达之前，我们必须加强防御。”",
    "dialogues": [
      {"text": "在支援到达之前，我们必须加强防御。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-038",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“把所有魔法师都调来。”",
    "dialogues": [
      {"text": "把所有魔法师都调来。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-039",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我有个主意。”",
    "dialogues": [
      {"text": "我有个主意。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-040",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“古籍中提到过，炎魔害怕圣水和银的组合物。”",
    "dialogues": [
      {"text": "古籍中提到过，炎魔害怕圣水和银的组合物。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-041",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“你能制作吗？”",
    "dialogues": [
      {"text": "你能制作吗？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-042",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“可以，但需要时间。”",
    "dialogues": [
      {"text": "可以，但需要时间。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-043",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们没有两天时间。”",
    "dialogues": [
      {"text": "我们没有两天时间。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-044",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“它来了。”",
    "dialogues": [
      {"text": "它来了。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-045",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“全体准备战斗！”",
    "dialogues": [
      {"text": "全体准备战斗！", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-046",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“它还有两个小时就会到达。”",
    "dialogues": [
      {"text": "它还有两个小时就会到达。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-047",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们能赢吗？”",
    "dialogues": [
      {"text": "我们能赢吗？", "speaker": "年轻骑士"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-048",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们必须赢。”",
    "dialogues": [
      {"text": "我们必须赢。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-049",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这是圣光药剂，能暂时增强你的力量。”",
    "dialogues": [
      {"text": "这是圣光药剂，能暂时增强你的力量。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-050",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“谢谢你，伊莉雅。”",
    "dialogues": [
      {"text": "谢谢你，伊莉雅。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-051",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“不会失败的。”",
    "dialogues": [
      {"text": "不会失败的。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-052",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“防线已经布置完毕。”",
    "dialogues": [
      {"text": "防线已经布置完毕。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-053",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“攻击！”",
    "dialogues": [
      {"text": "攻击！", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-054",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“退守内墙！”",
    "dialogues": [
      {"text": "退守内墙！", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-055",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“它的力量太强了。”",
    "dialogues": [
      {"text": "它的力量太强了。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-056",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“艾德温！”",
    "dialogues": [
      {"text": "艾德温！", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-057",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“赢了吗？”",
    "dialogues": [
      {"text": "赢了吗？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-058",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“赢了。”",
    "dialogues": [
      {"text": "赢了。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-059",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“城墙需要完全重建。”",
    "dialogues": [
      {"text": "城墙需要完全重建。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-060",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“王都的支援什么时候到？”",
    "dialogues": [
      {"text": "王都的支援什么时候到？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-061",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“预计明天。”",
    "dialogues": [
      {"text": "预计明天。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-062",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“他趁乱逃走了。”",
    "dialogues": [
      {"text": "他趁乱逃走了。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-063",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“黑暗势力正在集结，目标是王都。”",
    "dialogues": [
      {"text": "黑暗势力正在集结，目标是王都。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-064",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们必须提前警告国王。”",
    "dialogues": [
      {"text": "我们必须提前警告国王。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-065",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这场战争才刚刚开始。”",
    "dialogues": [
      {"text": "这场战争才刚刚开始。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-066",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“艾德温骑士，你的英勇事迹已经传遍王都。”",
    "dialogues": [
      {"text": "艾德温骑士，你的英勇事迹已经传遍王都。", "speaker": "雷纳德"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-067",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我只是做了该做的事。”",
    "dialogues": [
      {"text": "我只是做了该做的事。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-068",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“城墙需要重建，但人员伤亡不大。”",
    "dialogues": [
      {"text": "城墙需要重建，但人员伤亡不大。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-069",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这是证据。”",
    "dialogues": [
      {"text": "这是证据。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-070",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“必须立即报告国王。”",
    "dialogues": [
      {"text": "必须立即报告国王。", "speaker": "雷纳德"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-071",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们和你一起回去。”",
    "dialogues": [
      {"text": "我们和你一起回去。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-072",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“莫洛克的同党。”",
    "dialogues": [
      {"text": "莫洛克的同党。", "speaker": "雷纳德"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-073",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们必须尽快查出来。”",
    "dialogues": [
      {"text": "我们必须尽快查出来。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-074",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“为什么？”",
    "dialogues": [
      {"text": "为什么？", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-075",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“莫洛克承诺给我力量……”",
    "dialogues": [
      {"text": "莫洛克承诺给我力量……", "speaker": "托马斯"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-076",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“你背叛了圣光。”",
    "dialogues": [
      {"text": "你背叛了圣光。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-077",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“按军法处置。”",
    "dialogues": [
      {"text": "按军法处置。", "speaker": "加尔文"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-078",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“等等。”",
    "dialogues": [
      {"text": "等等。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-079",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“他可能有更多的情报。”",
    "dialogues": [
      {"text": "他可能有更多的情报。", "speaker": "伊莉雅"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-080",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“放过我的家人，他们什么都不知道。”",
    "dialogues": [
      {"text": "放过我的家人，他们什么都不知道。", "speaker": "托马斯"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-081",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我答应你。”",
    "dialogues": [
      {"text": "我答应你。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-082",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们必须立刻赶回王都。”",
    "dialogues": [
      {"text": "我们必须立刻赶回王都。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-083",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“勇敢的骑士们，感谢你们的到来。”",
    "dialogues": [
      {"text": "勇敢的骑士们，感谢你们的到来。", "speaker": "国王"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-084",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“陛下，黑暗势力正在集结。”",
    "dialogues": [
      {"text": "陛下，黑暗势力正在集结。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-085",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我们将组建一支新的联军，对抗黑暗。”",
    "dialogues": [
      {"text": "我们将组建一支新的联军，对抗黑暗。", "speaker": "国王"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-086",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“艾德温，你愿意担任先锋吗？”",
    "dialogues": [
      {"text": "艾德温，你愿意担任先锋吗？", "speaker": "国王"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-087",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“这是我的荣幸，陛下。”",
    "dialogues": [
      {"text": "这是我的荣幸，陛下。", "speaker": "艾德温"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-088",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“让我们为了光明，为了正义，为了这个世界！”",
    "dialogues": [
      {"text": "让我们为了光明，为了正义，为了这个世界！", "speaker": "国王"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-西幻-089",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“为了光明！”",
    "dialogues": [
      {"text": "为了光明！", "speaker": "众人"},
    ],
    "note": "来源: test_novel_western.txt | 风格: 西幻",
  },
  {
    "id": "GT-玄幻(斗破)-001",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“斗之力，三段！”",
    "dialogues": [
      {"text": "斗之力，三段！", "speaker": "测验魔石碑"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-002",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“萧炎，斗之力，三段！级别：低级！”",
    "dialogues": [
      {"text": "萧炎，斗之力，三段！级别：低级！", "speaker": "中年男子"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-003",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“下一个，萧媚！”",
    "dialogues": [
      {"text": "下一个，萧媚！", "speaker": "测验人"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-004",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“下一个，萧薰儿！”",
    "dialogues": [
      {"text": "下一个，萧薰儿！", "speaker": "测试员"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-005",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“萧炎哥哥。”",
    "dialogues": [
      {"text": "萧炎哥哥。", "speaker": "萧薰儿"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-006",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“我现在还有资格让你怎么叫么？”",
    "dialogues": [
      {"text": "我现在还有资格让你怎么叫么？", "speaker": "萧炎"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-007",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“萧炎哥哥，以前你曾经与薰儿说过，要能放下，才能拿起，提放自如，是自在人！”",
    "dialogues": [
      {"text": "萧炎哥哥，以前你曾经与薰儿说过，要能放下，才能拿起，提放自如，是自在人！", "speaker": "萧薰儿"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-008",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“呵呵，自在人？我也只会说而已，你看我现在的模样，象自在人吗？而且……这世界，本来就不属于我。”",
    "dialogues": [
      {"text": "呵呵，自在人？我也只会说而已，你看我现在的模样，象自在人吗？而且……这世界，本来就不属于我。", "speaker": "萧炎"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-009",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“萧炎哥哥，虽然并不知道你究竟是怎么回事，不过，薰儿相信，你会重新站起来，取回属于你的荣耀与尊严……”",
    "dialogues": [
      {"text": "萧炎哥哥，虽然并不知道你究竟是怎么回事，不过，薰儿相信，你会重新站起来，取回属于你的荣耀与尊严……", "speaker": "萧薰儿"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
  {
    "id": "GT-玄幻(斗破)-010",
    "source": "gt_json",
    "category": "dialogue",
    "paragraph": "“当年的萧炎哥哥，的确很吸引人……”",
    "dialogues": [
      {"text": "当年的萧炎哥哥，的确很吸引人……", "speaker": "萧薰儿"},
    ],
    "note": "来源: 斗破苍穹_前10章 | 风格: 玄幻(斗破)",
  },
]
